name: Docker Build

on:
  push:
    branches: [main]

env:
  REGISTRY_SERVER: git.dotnot.pl
  IMAGE_NAME: karol.kozlowski/workout-manager

jobs:
  build:
    runs-on: docker
    container:
      image: alpine:latest

    steps:
      - name: set up Docker CLI
        run: apk add --no-cache docker-cli git nodejs

      - name: checkout repository
        uses: actions/checkout@v4

      - name: login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_SERVER }}
          username: ${{ secrets.RELEASE_USER }}
          password: ${{ secrets.RELEASE_SECRET }}

      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:latest
